# https://docs.docker.com/compose/compose-file/

version: "3.7"
services:
  ruuvi-station-influx-gateway:
    build: ./
    image: ruuvi-station-influx-gateway:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000/tcp"
    depends_on: 
      - influxdb

  influxdb:
    image: influxdb:2.0.7
    ports:
      - 8086:8086
    restart: "unless-stopped"
    volumes:
      - ./influxdb:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on: 
      - influxdb
    restart: "unless-stopped"

volumes:
  grafana-storage: